// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLMHCdLmnYMF997X_-0N3ODNjDB5B8eWM',
    appId: '1:445862316836:web:ce06189ecbfa42f86601b1',
    messagingSenderId: '445862316836',
    projectId: 'bombastik-b4301',
    authDomain: 'bombastik-b4301.firebaseapp.com',
    storageBucket: 'bombastik-b4301.firebasestorage.app',
    measurementId: 'G-43YK4TPZKP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2Wo0REpje-G7P-7KkPAsFGnmXfE3g8Ng',
    appId: '1:445862316836:android:f36811669997f6d66601b1',
    messagingSenderId: '445862316836',
    projectId: 'bombastik-b4301',
    storageBucket: 'bombastik-b4301.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4_XbGPJvPt663DumJwGUxnAPCK7hn8Y8',
    appId: '1:445862316836:ios:2eaab3d0acb31f4b6601b1',
    messagingSenderId: '445862316836',
    projectId: 'bombastik-b4301',
    storageBucket: 'bombastik-b4301.firebasestorage.app',
    iosBundleId: 'com.example.bombastik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4_XbGPJvPt663DumJwGUxnAPCK7hn8Y8',
    appId: '1:445862316836:ios:2eaab3d0acb31f4b6601b1',
    messagingSenderId: '445862316836',
    projectId: 'bombastik-b4301',
    storageBucket: 'bombastik-b4301.firebasestorage.app',
    iosBundleId: 'com.example.bombastik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLMHCdLmnYMF997X_-0N3ODNjDB5B8eWM',
    appId: '1:445862316836:web:b1b473a57a15ee996601b1',
    messagingSenderId: '445862316836',
    projectId: 'bombastik-b4301',
    authDomain: 'bombastik-b4301.firebaseapp.com',
    storageBucket: 'bombastik-b4301.firebasestorage.app',
    measurementId: 'G-5L3BTPW5BT',
  );
}
